// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechTestWebApi.Data;

#nullable disable

namespace TechTestWebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("TechTestWebApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "An apple mobile which is nothing like apple",
                            Name = "iPhone 9",
                            Price = 549.0
                        },
                        new
                        {
                            Id = 2,
                            Description = "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
                            Name = "iPhone X",
                            Price = 899.0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Samsung's new variant which goes beyond Galaxy to the Universe",
                            Name = "Samsung Universe 9",
                            Price = 1249.0
                        },
                        new
                        {
                            Id = 4,
                            Description = "OPPO F19 is officially announced on April 2021.",
                            Name = "OPPOF19",
                            Price = 280.0
                        },
                        new
                        {
                            Id = 5,
                            Description = "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
                            Name = "Huawei P30",
                            Price = 499.0
                        },
                        new
                        {
                            Id = 6,
                            Description = "MacBook Pro 2021 with mini-LED display may launch between September, November",
                            Name = "MacBook Pro",
                            Price = 1749.0
                        },
                        new
                        {
                            Id = 7,
                            Description = "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
                            Name = "Samsung Galaxy Book",
                            Price = 1499.0
                        },
                        new
                        {
                            Id = 8,
                            Description = "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.",
                            Name = "Microsoft Surface Laptop 4",
                            Price = 1499.0
                        },
                        new
                        {
                            Id = 9,
                            Description = "Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty",
                            Name = "Infinix INBOOK",
                            Price = 1099.0
                        },
                        new
                        {
                            Id = 10,
                            Description = "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10",
                            Name = "HP Pavilion 15-DK1056WM",
                            Price = 1099.0
                        },
                        new
                        {
                            Id = 11,
                            Description = "Mega Discount, Impression of Acqua Di Gio by GiorgioArmani concentrated attar perfume Oil",
                            Name = "perfume Oil",
                            Price = 13.0
                        },
                        new
                        {
                            Id = 12,
                            Description = "Royal_Mirage Sport Brown Perfume for Men & Women - 120ml",
                            Name = "Brown Perfume",
                            Price = 40.0
                        },
                        new
                        {
                            Id = 13,
                            Description = "Product details of Best Fog Scent Xpressio Perfume 100ml For Men cool long lasting perfumes for Men",
                            Name = "Fog Scent Xpressio Perfume",
                            Price = 13.0
                        },
                        new
                        {
                            Id = 14,
                            Description = "Original Al Munakh® by Mahal Al Musk | Our Impression of Climate | 6ml Non-Alcoholic Concentrated Perfume Oil",
                            Name = "Non-Alcoholic Concentrated Perfume Oil",
                            Price = 120.0
                        },
                        new
                        {
                            Id = 15,
                            Description = "Genuine  Al-Rehab spray perfume from UAE/Saudi Arabia/Yemen High Quality",
                            Name = "Eau De Perfume Spray",
                            Price = 30.0
                        },
                        new
                        {
                            Id = 16,
                            Description = "L'OrÃ©al Paris introduces Hyaluron Expert Replumping Serum formulated with 1.5% Hyaluronic Acid",
                            Name = "Hyaluronic Acid Serum",
                            Price = 19.0
                        },
                        new
                        {
                            Id = 17,
                            Description = "Tea tree oil contains a number of compounds, including terpinen-4-ol, that have been shown to kill certain bacteria,",
                            Name = "Tree Oil 30ml",
                            Price = 12.0
                        },
                        new
                        {
                            Id = 18,
                            Description = "Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.",
                            Name = "Oil Free Moisturizer 100ml",
                            Price = 40.0
                        },
                        new
                        {
                            Id = 19,
                            Description = "Product name: rorec collagen hyaluronic acid white face serum riceNet weight: 15 m",
                            Name = "Skin Beauty Serum.",
                            Price = 46.0
                        },
                        new
                        {
                            Id = 20,
                            Description = "Fair & Clear is Pakistan's only pure Freckle cream which helpsfade Freckles, Darkspots and pigments. Mercury level is 0%, so there are no side effects.",
                            Name = "Freckle Treatment Cream- 15gm",
                            Price = 70.0
                        },
                        new
                        {
                            Id = 21,
                            Description = "Fine quality Branded Product Keep in a cool and dry place",
                            Name = "- Daal Masoor 500 grams",
                            Price = 20.0
                        },
                        new
                        {
                            Id = 22,
                            Description = "Product details of Bake Parlor Big Elbow Macaroni - 400 gm",
                            Name = "Elbow Macaroni - 400 gm",
                            Price = 14.0
                        },
                        new
                        {
                            Id = 23,
                            Description = "Specifications of Orange Essence Food Flavour For Cakes and Baking Food Item",
                            Name = "Orange Essence Food Flavou",
                            Price = 14.0
                        },
                        new
                        {
                            Id = 24,
                            Description = "original fauji cereal muesli 250gm box pack original fauji cereals muesli fruit nuts flakes breakfast cereal break fast faujicereals cerels cerel foji fouji",
                            Name = "cereals muesli fruit nuts",
                            Price = 46.0
                        },
                        new
                        {
                            Id = 25,
                            Description = "Dry Rose Flower Powder Gulab Powder 50 Gram • Treats Wounds",
                            Name = "Gulab Powder 50 Gram",
                            Price = 70.0
                        },
                        new
                        {
                            Id = 26,
                            Description = "Boho Decor Plant Hanger For Home Wall Decoration Macrame Wall Hanging Shelf",
                            Name = "Plant Hanger For Home",
                            Price = 41.0
                        },
                        new
                        {
                            Id = 27,
                            Description = "Package Include 6 Birds with Adhesive Tape Shape: 3D Shaped Wooden Birds Material: Wooden MDF, Laminated 3.5mm",
                            Name = "Flying Wooden Bird",
                            Price = 51.0
                        },
                        new
                        {
                            Id = 28,
                            Description = "3D led lamp sticker Wall sticker 3d wall art light on/off button  cell operated (included)",
                            Name = "3D Embellishment Art Lamp",
                            Price = 20.0
                        },
                        new
                        {
                            Id = 29,
                            Description = "Handcraft Chinese style art luxury palace hotel villa mansion home decor ceramic vase with brass fruit plate",
                            Name = "Handcraft Chinese style",
                            Price = 60.0
                        },
                        new
                        {
                            Id = 30,
                            Description = "Attractive DesignMetallic materialFour key hooksReliable & DurablePremium Quality",
                            Name = "Key Holder",
                            Price = 30.0
                        },
                        new
                        {
                            Id = 31,
                            Description = "Mornadi Velvet Bed Base with Headboard Slats Support Classic Style Bedroom Furniture Bed Set",
                            Name = "Mornadi Velvet Bed",
                            Price = 40.0
                        },
                        new
                        {
                            Id = 32,
                            Description = "Ratttan Outdoor furniture Set Waterproof  Rattan Sofa for Coffe Cafe",
                            Name = "Sofa for Coffe Cafe",
                            Price = 50.0
                        },
                        new
                        {
                            Id = 33,
                            Description = "3 Tier Corner Shelves | 3 PCs Wall Mount Kitchen Shelf | Floating Bedroom Shelf",
                            Name = "3 Tier Corner Shelves",
                            Price = 700.0
                        },
                        new
                        {
                            Id = 34,
                            Description = "V﻿ery good quality plastic table for multi purpose now in reasonable price",
                            Name = "Plastic Table",
                            Price = 50.0
                        },
                        new
                        {
                            Id = 35,
                            Description = "Material: Stainless Steel and Fabric  Item Size: 110 cm x 45 cm x 175 cm Package Contents: 1 Storage Wardrobe",
                            Name = "3 DOOR PORTABLE",
                            Price = 41.0
                        },
                        new
                        {
                            Id = 36,
                            Description = "Cotton Solid Color Professional Wear Sleeve Shirt Womens Work Blouses Wholesale Clothing Casual Plain Custom Top OEM Customized",
                            Name = "Sleeve Shirt Womens",
                            Price = 90.0
                        },
                        new
                        {
                            Id = 37,
                            Description = "PACK OF 3 CAMISOLES ,VERY COMFORTABLE SOFT COTTON STUFF, COMFORTABLE IN ALL FOUR SEASONS",
                            Name = "ank Tops for Womens/Girls",
                            Price = 50.0
                        },
                        new
                        {
                            Id = 38,
                            Description = "sublimation plain kids tank tops wholesale",
                            Name = "sublimation plain kids tank",
                            Price = 100.0
                        },
                        new
                        {
                            Id = 39,
                            Description = "2021 Custom Winter Fall Zebra Knit Crop Top Women Sweaters Wool Mohair Cos Customize Crew Neck Women' S Crop Top Sweater",
                            Name = "Women Sweaters Wool",
                            Price = 600.0
                        },
                        new
                        {
                            Id = 40,
                            Description = "women winter clothes thick fleece hoodie top with sweat pantjogger women sweatsuit set joggers pants two piece pants set",
                            Name = "women winter clothes",
                            Price = 57.0
                        },
                        new
                        {
                            Id = 41,
                            Description = "NIGHT SUIT RED MICKY MOUSE..  For Girls. Fantastic Suits.",
                            Name = "NIGHT SUIT",
                            Price = 55.0
                        },
                        new
                        {
                            Id = 42,
                            Description = "FABRIC: LILEIN CHEST: 21 LENGHT: 37 TROUSER: (38) :ARABIC LILEIN",
                            Name = "Stiched Kurta plus trouser",
                            Price = 80.0
                        },
                        new
                        {
                            Id = 43,
                            Description = "Ghazi fabric long frock gold printed ready to wear stitched collection (G992)",
                            Name = "frock gold printed",
                            Price = 600.0
                        },
                        new
                        {
                            Id = 44,
                            Description = "This classy shirt for women gives you a gorgeous look on everyday wear and specially for semi-casual wears.",
                            Name = "Ladies Multicolored Dress",
                            Price = 79.0
                        },
                        new
                        {
                            Id = 45,
                            Description = "Ready to wear, Unique design according to modern standard fashion, Best fitting ,Imported stuff",
                            Name = "Malai Maxi Dress",
                            Price = 50.0
                        },
                        new
                        {
                            Id = 46,
                            Description = "Close: Lace, Style with bottom: Increased inside, Sole Material: Rubber",
                            Name = "women's shoes",
                            Price = 40.0
                        },
                        new
                        {
                            Id = 47,
                            Description = "Synthetic Leather Casual Sneaker shoes for Women/girls Sneakers For Women",
                            Name = "Sneaker shoes",
                            Price = 120.0
                        },
                        new
                        {
                            Id = 48,
                            Description = "Features: Flip-flops, Mid Heel, Comfortable, Striped Heel, Antiskid, Striped",
                            Name = "Women Strip Heel",
                            Price = 40.0
                        },
                        new
                        {
                            Id = 49,
                            Description = "Womens Chappals & Shoe Ladies Metallic Tong Thong Sandal Flat Summer 2020 Maasai Sandals",
                            Name = "Chappals & Shoe Ladies Metallic",
                            Price = 23.0
                        },
                        new
                        {
                            Id = 50,
                            Description = "2020 New Arrivals Genuine Leather Fashion Trend Platform Summer Women Shoes",
                            Name = "Women Shoes",
                            Price = 36.0
                        },
                        new
                        {
                            Id = 51,
                            Description = "Many store is creating new designs and trend every month and every year. Daraz.pk have a beautiful range of men fashion brands",
                            Name = "half sleeves T shirts",
                            Price = 23.0
                        },
                        new
                        {
                            Id = 52,
                            Description = "quality and professional print - It doesn't just look high quality, it is high quality.",
                            Name = "FREE FIRE T Shirt",
                            Price = 10.0
                        },
                        new
                        {
                            Id = 53,
                            Description = "Brand: vintage Apparel ,Export quality",
                            Name = "printed high quality T shirts",
                            Price = 35.0
                        },
                        new
                        {
                            Id = 54,
                            Description = "Product Description Features: 100% Ultra soft Polyester Jersey. Vibrant & colorful printing on front. Feels soft as cotton without ever cracking",
                            Name = "Pubg Printed Graphic T-Shirt",
                            Price = 46.0
                        },
                        new
                        {
                            Id = 55,
                            Description = "Fabric Jercy, Size: M & L Wear Stylish Dual Stiched",
                            Name = "Money Heist Printed Summer T Shirts",
                            Price = 66.0
                        },
                        new
                        {
                            Id = 56,
                            Description = "Gender: Men , Colors: Same as DisplayedCondition: 100% Brand New",
                            Name = "Sneakers Joggers Shoes",
                            Price = 40.0
                        },
                        new
                        {
                            Id = 57,
                            Description = "Men Shoes - Loafers for men - Rubber Shoes - Nylon Shoes - Shoes for men - Moccassion - Pure Nylon (Rubber) Expot Quality.",
                            Name = "Loafers for men",
                            Price = 47.0
                        },
                        new
                        {
                            Id = 58,
                            Description = "Pattern Type: Solid, Material: PU, Toe Shape: Pointed Toe ,Outsole Material: Rubber",
                            Name = "formal offices shoes",
                            Price = 57.0
                        },
                        new
                        {
                            Id = 59,
                            Description = "Comfortable stretch cloth, lightweight body; ,rubber sole, anti-skid wear;",
                            Name = "Spring and summershoes",
                            Price = 20.0
                        },
                        new
                        {
                            Id = 60,
                            Description = "High Quality ,Stylish design ,Comfortable wear ,FAshion ,Durable",
                            Name = "Stylish Casual Jeans Shoes",
                            Price = 58.0
                        },
                        new
                        {
                            Id = 61,
                            Description = "Style:Sport ,Clasp:Buckles ,Water Resistance Depth:3Bar",
                            Name = "Leather Straps Wristwatch",
                            Price = 120.0
                        },
                        new
                        {
                            Id = 62,
                            Description = "Watch Crown With Environmental IPS Bronze Electroplating; Display system of 12 hours",
                            Name = "Waterproof Leather Brand Watch",
                            Price = 46.0
                        },
                        new
                        {
                            Id = 63,
                            Description = "Men Silver Chain Royal Blue Premium Watch Latest Analog Watch",
                            Name = "Royal Blue Premium Watch",
                            Price = 50.0
                        },
                        new
                        {
                            Id = 64,
                            Description = "Leather Strap Skeleton Watch for Men - Stylish and Latest Design",
                            Name = "Leather Strap Skeleton Watch",
                            Price = 46.0
                        },
                        new
                        {
                            Id = 65,
                            Description = "Stylish Watch For Man (Luxury) Classy Men's Stainless Steel Wrist Watch - Box Packed",
                            Name = "Stainless Steel Wrist Watch",
                            Price = 47.0
                        },
                        new
                        {
                            Id = 66,
                            Description = "Elegant design, Stylish ,Unique & Trendy,Comfortable wear",
                            Name = "Steel Analog Couple Watches",
                            Price = 35.0
                        },
                        new
                        {
                            Id = 67,
                            Description = "Buy this awesome  The product is originally manufactured by the company and it's a top selling product with a very reasonable",
                            Name = "Fashion Magnetic Wrist Watch",
                            Price = 60.0
                        },
                        new
                        {
                            Id = 68,
                            Description = "Stylish Luxury Digital Watch For Girls / Women - Led Smart Ladies Watches For Girls",
                            Name = "Stylish Luxury Digital Watch",
                            Price = 57.0
                        },
                        new
                        {
                            Id = 69,
                            Description = "Product details of Golden Watch Pearls Bracelet Watch For Girls - Golden Chain Ladies Bracelate Watch for Women",
                            Name = "Golden Watch Pearls Bracelet Watch",
                            Price = 47.0
                        },
                        new
                        {
                            Id = 70,
                            Description = "Fashion Skmei 1830 Shell Dial Stainless Steel Women Wrist Watch Lady Bracelet Watch Quartz Watches Ladies",
                            Name = "Stainless Steel Women",
                            Price = 35.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
